# Generated by Django 3.2 on 2021-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_yamdbuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.CharField(choices=[('usr', 'user'), ('mod', 'moderator'), ('adm', 'admin')], default='usr', max_length=10),
        ),
    ]
